#Load / Save Settings for the Rpg Suite of plugins
Auto Update: true
Use Mysql: false
MySql DataBase:
  User: usernamehere
  Password: passwordgoeshere
  #leave this line alone if you don't know what it means
  CharacterEncoding: ISO-8859-1
  #leave this line alone if you don't know what it means
  UseUnicode: true
  Url: 'jdbc:mysql://your.database.address/goes_here'
Plugins:
  Guilds: false
  Chat: false
  Poisoned Earth: false
  Classes: false
  Races: false
  Achievements: false
  Food: false
  Party: false
  #click must be true to use minions
  Minions: false
  Click: false
  Friends: false
  Lobby: false
  Quest: false
  Spawns: false
  Warps: false
  Trade: false
  Border: false
  Reputations: false
  Permissions: false
  Vector Blocks: false